apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-deployment
  labels:
    app: crm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
      - name: crm-container
        image: crm-service:latest
        ports:
        - containerPort: 8081
        env:
          - name: REACTIVE_MODE
            value: "true"
